// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQB1fwkXjg4_hlM0pZU8o58i2F-zUTJI',
    appId: '1:983085595486:web:d2e2f79e199557f9466dcf',
    messagingSenderId: '983085595486',
    projectId: 'dashboard-54034',
    authDomain: 'dashboard-54034.firebaseapp.com',
    storageBucket: 'dashboard-54034.firebasestorage.app',
    measurementId: 'G-GX4BVXT4T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1IiY_WdWDBIOCb6HWrBlVWsajttx9Aw',
    appId: '1:983085595486:android:9693360a379b0bc3466dcf',
    messagingSenderId: '983085595486',
    projectId: 'dashboard-54034',
    storageBucket: 'dashboard-54034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjuVEj-cV_oORUvIH4I84C1lWpNoucn0',
    appId: '1:983085595486:ios:e94445c58a2e0a72466dcf',
    messagingSenderId: '983085595486',
    projectId: 'dashboard-54034',
    storageBucket: 'dashboard-54034.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpjuVEj-cV_oORUvIH4I84C1lWpNoucn0',
    appId: '1:983085595486:ios:e94445c58a2e0a72466dcf',
    messagingSenderId: '983085595486',
    projectId: 'dashboard-54034',
    storageBucket: 'dashboard-54034.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNQB1fwkXjg4_hlM0pZU8o58i2F-zUTJI',
    appId: '1:983085595486:web:6e944222837ea8c5466dcf',
    messagingSenderId: '983085595486',
    projectId: 'dashboard-54034',
    authDomain: 'dashboard-54034.firebaseapp.com',
    storageBucket: 'dashboard-54034.firebasestorage.app',
    measurementId: 'G-8VEQ4115PV',
  );
}
